// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/bluetooth.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BluetoothClient is the client API for Bluetooth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BluetoothClient interface {
	GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Devices, error)
	ConnectDevice(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Response, error)
	DisconnectDevice(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Response, error)
}

type bluetoothClient struct {
	cc grpc.ClientConnInterface
}

func NewBluetoothClient(cc grpc.ClientConnInterface) BluetoothClient {
	return &bluetoothClient{cc}
}

func (c *bluetoothClient) GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Devices, error) {
	out := new(Devices)
	err := c.cc.Invoke(ctx, "/grpc.Bluetooth/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothClient) ConnectDevice(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Bluetooth/ConnectDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bluetoothClient) DisconnectDevice(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Bluetooth/DisconnectDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BluetoothServer is the server API for Bluetooth service.
// All implementations must embed UnimplementedBluetoothServer
// for forward compatibility
type BluetoothServer interface {
	GetDevices(context.Context, *Empty) (*Devices, error)
	ConnectDevice(context.Context, *ConnectRequest) (*Response, error)
	DisconnectDevice(context.Context, *DisconnectRequest) (*Response, error)
	mustEmbedUnimplementedBluetoothServer()
}

// UnimplementedBluetoothServer must be embedded to have forward compatible implementations.
type UnimplementedBluetoothServer struct {
}

func (UnimplementedBluetoothServer) GetDevices(context.Context, *Empty) (*Devices, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedBluetoothServer) ConnectDevice(context.Context, *ConnectRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectDevice not implemented")
}
func (UnimplementedBluetoothServer) DisconnectDevice(context.Context, *DisconnectRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectDevice not implemented")
}
func (UnimplementedBluetoothServer) mustEmbedUnimplementedBluetoothServer() {}

// UnsafeBluetoothServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BluetoothServer will
// result in compilation errors.
type UnsafeBluetoothServer interface {
	mustEmbedUnimplementedBluetoothServer()
}

func RegisterBluetoothServer(s grpc.ServiceRegistrar, srv BluetoothServer) {
	s.RegisterService(&Bluetooth_ServiceDesc, srv)
}

func _Bluetooth_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Bluetooth/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServer).GetDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bluetooth_ConnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServer).ConnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Bluetooth/ConnectDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServer).ConnectDevice(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bluetooth_DisconnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BluetoothServer).DisconnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Bluetooth/DisconnectDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BluetoothServer).DisconnectDevice(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bluetooth_ServiceDesc is the grpc.ServiceDesc for Bluetooth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bluetooth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Bluetooth",
	HandlerType: (*BluetoothServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _Bluetooth_GetDevices_Handler,
		},
		{
			MethodName: "ConnectDevice",
			Handler:    _Bluetooth_ConnectDevice_Handler,
		},
		{
			MethodName: "DisconnectDevice",
			Handler:    _Bluetooth_DisconnectDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bluetooth.proto",
}
